//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestToolsBase.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TestToolsBase.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is some error with the Windows Account Service - User: {0}.
        /// </summary>
        internal static string ACCOUNT_MANAGEMENT_ERROR {
            get {
                return ResourceManager.GetString("ACCOUNT_MANAGEMENT_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use /detailed argument for detailed logging.
        /// </summary>
        internal static string ARG_HELP_DETAILED {
            get {
                return ResourceManager.GetString("ARG_HELP_DETAILED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This help message can be show by: /? /h /help.
        /// </summary>
        internal static string ARG_HELP_HELP {
            get {
                return ResourceManager.GetString("ARG_HELP_HELP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visszatöltéshez használja a /sql:X argumentumot.
        /// </summary>
        internal static string ARG_HELP_SQL {
            get {
                return ResourceManager.GetString("ARG_HELP_SQL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use /help:continue.
        /// </summary>
        internal static string ARG_HELP_SQL_CONTINUABLE {
            get {
                return ResourceManager.GetString("ARG_HELP_SQL_CONTINUABLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To work with testDB use this argument: /tesztDB.
        /// </summary>
        internal static string ARG_HELP_TEST_DB {
            get {
                return ResourceManager.GetString("ARG_HELP_TEST_DB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The checked value is under the defined limit..
        /// </summary>
        internal static string CHECKEDVALUE_ABOVE_LIMIT {
            get {
                return ResourceManager.GetString("CHECKEDVALUE_ABOVE_LIMIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The checked value is below the limit.
        /// </summary>
        internal static string CHECKEDVALUE_BELOW_LIMIT {
            get {
                return ResourceManager.GetString("CHECKEDVALUE_BELOW_LIMIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value: {0} HiLimit: {1} LowLimit: {2} Strings: {3}.
        /// </summary>
        internal static string CHECKEDVALUE_TOSTRING {
            get {
                return ResourceManager.GetString("CHECKEDVALUE_TOSTRING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The checked value is in the defined limit.
        /// </summary>
        internal static string CHECKEDVALUE_WITHIN_LIMIT {
            get {
                return ResourceManager.GetString("CHECKEDVALUE_WITHIN_LIMIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are u sure to cancel?.
        /// </summary>
        internal static string ConsoleApplication_CancelQuestion {
            get {
                return ResourceManager.GetString("ConsoleApplication_CancelQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The execution of the programm has cancelled.
        /// </summary>
        internal static string ConsoleApplication_ProgramEndCanceled {
            get {
                return ResourceManager.GetString("ConsoleApplication_ProgramEndCanceled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The details of the errors during the program execution.
        /// </summary>
        internal static string ConsoleApplication_ProgramEndErrorSummary {
            get {
                return ResourceManager.GetString("ConsoleApplication_ProgramEndErrorSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The program execution has failed.
        /// </summary>
        internal static string ConsoleApplication_ProgramEndFailed {
            get {
                return ResourceManager.GetString("ConsoleApplication_ProgramEndFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The program executed without any error.
        /// </summary>
        internal static string ConsoleApplication_ProgramEndOk {
            get {
                return ResourceManager.GetString("ConsoleApplication_ProgramEndOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trace file saved.
        /// </summary>
        internal static string ConsoleApplication_TracefileSavedInfo {
            get {
                return ResourceManager.GetString("ConsoleApplication_TracefileSavedInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please press any key....
        /// </summary>
        internal static string CONSOLEHELPER_PRESSANYKEY {
            get {
                return ResourceManager.GetString("CONSOLEHELPER_PRESSANYKEY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel operation.
        /// </summary>
        internal static string DIALOG_RESULT_CANCEL {
            get {
                return ResourceManager.GetString("DIALOG_RESULT_CANCEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No answer.
        /// </summary>
        internal static string DIALOG_RESULT_NO {
            get {
                return ResourceManager.GetString("DIALOG_RESULT_NO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK operation.
        /// </summary>
        internal static string DIALOG_RESULT_OK {
            get {
                return ResourceManager.GetString("DIALOG_RESULT_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retry operation.
        /// </summary>
        internal static string DIALOG_RESULT_RETRY {
            get {
                return ResourceManager.GetString("DIALOG_RESULT_RETRY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to YES answer.
        /// </summary>
        internal static string DIALOG_RESULT_YES {
            get {
                return ResourceManager.GetString("DIALOG_RESULT_YES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error happened: {0}.
        /// </summary>
        internal static string ERROR_HAPPENED_PARAM {
            get {
                return ResourceManager.GetString("ERROR_HAPPENED_PARAM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimum length is: {0}.
        /// </summary>
        internal static string ERROR_MIN_LENGHT {
            get {
                return ResourceManager.GetString("ERROR_MIN_LENGHT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No connection to the database since {0}.
        /// </summary>
        internal static string EXCEPTION_SQL_NO_DATA_FOR {
            get {
                return ResourceManager.GetString("EXCEPTION_SQL_NO_DATA_FOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No connectionn to the database in the last few hours.
        /// </summary>
        internal static string EXCEPTION_SQL_NO_DATA_FOR_WITHIN_HOURS {
            get {
                return ResourceManager.GetString("EXCEPTION_SQL_NO_DATA_FOR_WITHIN_HOURS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error! No such row at the table.
        /// </summary>
        internal static string EXCEPTION_SQL_NO_ROW_AT_TABLE {
            get {
                return ResourceManager.GetString("EXCEPTION_SQL_NO_ROW_AT_TABLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Result is successfull.
        /// </summary>
        internal static string MEASURE_SUCCESSFULL {
            get {
                return ResourceManager.GetString("MEASURE_SUCCESSFULL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Result is not succesfull.
        /// </summary>
        internal static string MEASURE_UNSUCCESSFULL {
            get {
                return ResourceManager.GetString("MEASURE_UNSUCCESSFULL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Measuring is on progress.
        /// </summary>
        internal static string MEASURING {
            get {
                return ResourceManager.GetString("MEASURING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nincs beállítva!.
        /// </summary>
        internal static string NOT_SET {
            get {
                return ResourceManager.GetString("NOT_SET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit program.
        /// </summary>
        internal static string QUIT {
            get {
                return ResourceManager.GetString("QUIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Trace file.
        /// </summary>
        internal static string SAVE_TRACE {
            get {
                return ResourceManager.GetString("SAVE_TRACE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keresési értékek.
        /// </summary>
        internal static string SEARCHING_VALUES {
            get {
                return ResourceManager.GetString("SEARCHING_VALUES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Process Details.
        /// </summary>
        internal static string SHOW_MEASURE_INFO {
            get {
                return ResourceManager.GetString("SHOW_MEASURE_INFO", resourceCulture);
            }
        }
    }
}
